// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvbwpghpzbdwxorlnvuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2YndwZ2hwemJkd3hvcmxudnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDc2NzIsImV4cCI6MjA2MDM4MzY3Mn0.rnnJkjBTq1pgRk51uVT3ViwWwRzNz1GJoeYdittSBa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);